trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    #!/bin/bash

ORG_OR_USER="your_org_or_user"

# CSV file to store user and repository associations
CSV_FILE="user_repo_associations.csv"

# Initialize CSV file
echo "Repository,User" > $CSV_FILE

# Read repositories from CSV file and loop through each repository
tail -n +2 repositories.csv | while IFS=',' read -r REPO; do
  # Fetch collaborators for the repository
  USERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$ORG_OR_USER/$REPO/collaborators" | jq -r '.[].login')

  # Store user and repository associations in CSV file
  for USER in $USERS; do
    echo "$REPO,$USER" >> $CSV_FILE
  done

  # Modify repository permissions
  for USER in $USERS; do
    if [[ $USER != "except_this_user" ]]; then
      curl -X PUT -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/$ORG_OR_USER/$REPO/collaborators/$USER" \
      -d '{"permission":"read"}'
    fi
  done
done

echo "Process completed. Check $CSV_FILE for user and repository associations."


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/user_repo_associations.csv'
    artifact: 'myArtifacts'
    publishLocation: pipeline
  displayName: 'Publish Artifacts'
