trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    #!/bin/bash
    ORG="sdevops713"
    CSV_FILE="user_repo_associations.csv"

    # Initialize CSV file
    echo "Repository,User" > $CSV_FILE

    # Read repositories from CSV file and loop through each repository
    tail -n +2 repositories.csv.xlsx | while IFS=',' read -r REPO; do
    # Fetch collaborators for the repository
    USERS=$(curl -s -H "Authorization: token $(TOKEN)" "https://api.github.com/repos/$ORG/$REPO/collaborators" | jq -r '.[].login')
    # Store user and repository associations in CSV file
    for USER in $USERS; do
    echo "$REPO,$USER" >> $CSV_FILE
    done

    # Modify repository permissions
    for USER in $USERS; do
    if [[ $USER != "teamdevops128" ]]; then
      curl -X PUT -H "Authorization: token $(TOKEN)" -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/$ORG/$REPO/collaborators/$USER" \
      -d '{"permission":"read"}'
    fi
    done
    done

    echo "Process completed. Check $CSV_FILE for user and repository associations."

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/user_repo_associations.csv'
    artifact: 'myArtifacts'
    publishLocation: pipeline
  displayName: 'Publish Artifacts'
